### ISSUE TITLE
Make verification trigger configurable. 

### ISSUE THREAD

**Issue by danieldietsch** [FahrJo/ultimate-automizer-vscode#13]
As verification is in general rather expensive, it is unfortunate that it is triggered for every save. It would be nicer (in particular for the backend) if verification would only be triggered manually.

**Comment by FahrJo** [comment]
Should be solved with v0.1.2 (38d59b0) now. Unfortunately, the "old" ultimate backend does not work at the moment (returns "failed to run ULTIMATE\njava.lang.NullPointerException\nnull") and compatibility for the new backend is not yet implemented.
